Blog/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

blogs/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'blogs'
urlpatterns = [
    # Домашняя страница
    path('', views.index, name='index'),
    # Страница со списком всех записей.
    path('posts/', views.posts, name='posts'),
    # Страница с конкретной записью
    path('posts/<int:post_id>', views.post, name='post'),
    # Страница для создания поста
    path('new_post', views.new_post, name='new_post'),
    # Страница для редактирования поста
    path('edit_post/<int:post_id>', views.edit_post, name='edit_post'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # Включить URL авторизации по умолчанию.
    path('', include('django.contrib.auth.urls')),
    # Страница регистрации.
    path('register/', views.register, name='register'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Возвращает строковое представление модели."""
        return self.title

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import  forms
from .models import BlogPost


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        labels = {'title': 'Title:', 'text': 'Text:'}

blogs/views.py
from django.shortcuts import render, redirect
from .models import BlogPost
from .forms import BlogPostForm
from django.contrib.auth.decorators import login_required
from django.http import Http404


# Create your views here.
def index(request):
    """Домашняя страница"""
    return render(request, 'blogs/index.html')

def posts(request):
    """Список постов"""
    posts = BlogPost.objects.order_by('date_added')
    context = {'posts': posts}
    return render(request, 'blogs/posts.html', context)

def post(request, post_id):
    post = BlogPost.objects.get(id=post_id)
    context = {'post':post}
    return render(request, 'blogs/post.html', context)

@login_required
def new_post(request):
    if request.method != 'POST':
        form = BlogPostForm()
    else:
        form = BlogPostForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:posts')
    context = {'form': form}
    return render(request, 'blogs/new_post.html', context)

@login_required
def edit_post(request, post_id):
    post = BlogPost.objects.get(id=post_id)
    if post.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = BlogPostForm(instance=post)
    else:
        form = BlogPostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:post', post_id=post_id)
    context = {'post': post, 'form': form}
    return render(request, 'blogs/edit_post.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Регистрирует нового пользователя."""
    if request.method != 'POST':
        # Выводит пустую форму регистрации.
        form = UserCreationForm()
    else:
        # Обработка заполненной формы.
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # Выполнение входа и перенаправление на домашнюю страницу.
            login(request, new_user)
            return redirect('blogs:index')
    # Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

blogs/templates/blogs/base.html
<p>
    <a href="{% url 'blogs:index' %}">Blog</a> -
    <a href="{% url 'blogs:posts' %}">Posts</a>

    {% if user.is_authenticated %}
        Hello, {{ user.username }}.
        <a href="{% url 'users:logout' %}">log out</a>
    {% else %}
        <a href="{% url 'users:register' %}">Register</a> -
        <a href="{% url 'users:login' %}">log in</a>
    {% endif %}

</p>
{% block content %}{% endblock content %}

blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}
{% block content %}

	<p>Edit your post:</p>
	<form action="{% url 'blogs:edit_post' post.id %}" method='post'>
	{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">Edit</button>
	</form>

{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}
{% block content %}
    <p>Blog helps you!</p>
{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}
{% block content %}

	<p>Create a new post:</p>
	<form action="{% url 'blogs:new_post' %}" method='post'>
	{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">Create</button>
	</form>

{% endblock content %}

blogs/templates/blogs/post.html
{% extends 'blogs/base.html' %}
{% block content %}
  <p>{{ post }}</p>
  <p>{{ post.date_added|date:'M d, Y H:i' }}</p>
  <p>{{ post.text|linebreaks }}</p>
  <a href="{% url 'blogs:edit_post' post.id %}">Edit</a>
{% endblock content %}

blogs/templates/blogs/posts.html
{% extends "blogs/base.html" %}
{% block content %}
  <p>Posts</p>

  <a href="{% url 'blogs:new_post' %}">Create a new post</a>

  <ul>
    {% for post in posts %}
      <li>
        <a href="{% url 'blogs:post' post.id %}">{{ post }}</a>
      </li>
    {% empty %}
      <li>No posts ¯\_(ツ)_/¯</li>
    {% endfor %}
  </ul>
{% endblock content %}